API_ID: 
API_HASH: 
BOT_TOKEN: 


MONGO_URL: 
REDIS_URI:
REDIS_PORT:
REDIS_PASS:

SESSION_API_ID: 
SESSION_API_HASH: 
SESSION_STRING: 

ADMINS: 
  - 1739206386

OWNER: 1739206386

BOT_PIC: https://telegra.ph/file/e33abcbe17dcf9814c734.jpg
OWNER_PIC: https://telegra.ph/file/802b2b1c3b4507d3b32cf.jpg


SUPPORT_CHAT: ccxenchat
# LOG_CHAT: 
LOG_CHAT: 



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"

